project_name: rpc-snooper

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/snooper
    binary: snooper-{{.Version}}
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goarch: "386"
      # broken with go-ethereum github.com/prometheus/tsdb module
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/ethpandaops/rpc-snooper/utils.BuildRelease={{.Tag}} -X github.com/ethpandaops/rpc-snooper/utils.BuildVersion={{.ShortCommit}}
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
